# Generated by Django 2.2.5 on 2019-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='gate_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
